typography_spectrum: 0.9108951999805868
color:
  brandColors:
    - '#020200'
    - '#405f74'
    - '#ff960a'
    - '#ffff8f'
    - '#9e1400'
  brandStrength: 0
  lightness: 0.6875
  saturation: 0.1875
  rhythmicContrast: 0.5
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0.46983255352824926
analytics:
  google: UA-79446615-1
  facebook: null
  twitter: null
name: Connie Main Duarte
cta:
  domain: null
  bucket: null
  version: null
navigation:
  - name: About
    id: be3b8347-46c0-4ef9-ae74-0c275810b972
    type: content
favicon: null
title: Headline
description: ''
purpose: []
