name: Connie Main Duarte
favicon: null
layout_spectrum: 0.429489680333063
typography_spectrum: 0.66008
title: Connie Main Duarte
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: UA-79446615-1
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ADD7F6'
    - '#87BFFF'
    - '#3F8EFC'
    - '#2667FF'
    - '#3B28CC'
  brandStrength: 0.4375
  lightness: 0.75
  saturation: 0.375
  rhythmicContrast: 0.25
purpose: []
