name: Connie Main Duarte
favicon: null
layout_spectrum: 0.49091
typography_spectrum: 0.62783
title: Connie Main Duarte
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: UA-79446615-1
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#020200'
    - '#405f74'
    - '#ff960a'
    - '#ffff8f'
    - '#9e1400'
  brandStrength: 0
  lightness: 0.6875
  saturation: 0.1875
  rhythmicContrast: 0.5
purpose: []
