layout_spectrum: 0.27699228352867067
typography_spectrum: 0.11221421440131962
color:
  brandColors:
    - '#225378'
    - '#1695A3'
    - '#ACF0F2'
    - '#F3FFE2'
    - '#EB7F00'
  brandStrength: 0.2790265940129757
  lightness: 0.801439831033349
  saturation: 0.9926840562839061
  rhythmicContrast: 0.16482308972626925
opengraph:
  image: null
  type: null
  appId: null
analytics:
  google: UA-79446615-1
  facebook: null
  twitter: null
name: Connie Main Duarte
cta:
  domain: null
  bucket: null
  version: null
navigation:
  - name: About
    id: be3b8347-46c0-4ef9-ae74-0c275810b972
    type: content
favicon: null
title: ''
description: ''
purpose: []
