name: Connie Main Duarte
favicon: null
layout_spectrum: 0.429489680333063
typography_spectrum: 0.66008
title: Connie Main Duarte
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: UA-79446615-1
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#fefefe'
    - '#d6d6d4'
    - '#939592'
    - '#5a5b5f'
  brandStrength: 0.625
  lightness: 0.75
  saturation: 0.125
  rhythmicContrast: 0.5
purpose: []
