name: Connie Main Duarte
favicon: null
layout_spectrum: 0.49091
typography_spectrum: 0.6348
title: Connie Main Duarte
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: UA-79446615-1
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#4b7291'
    - '#97a29e'
    - '#939228'
    - '#e7ece6'
    - '#141f1b'
  brandStrength: 0.875
  lightness: 0.5
  saturation: 0
  rhythmicContrast: 0.5
purpose: []
